name: Feature Request
description: Suggest an idea or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        This template is for requests specific to https://docs.stjude.cloud.
        If you have a request related to St. Jude Cloud that is not specific to the documentation site, please contact [support@stjude.cloud](mailto:support@stjude.cloud).
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Is your feature request related to a problem? Describe it.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, mockups, or anything else relevant.
    validations:
      required: false
