name: Bot

on:
  issue_comment:
    types: [created]

permissions: {}

jobs:
  bot:
    name: bot-processor
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      actions: write
    steps:
      - name: checkout
        uses: actions/checkout@v4 # required to make the script available for next step

      - name: comment analyzer
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.CLOUDY_TOKEN}}
          script: |
            const script = require('./.github/scripts/bot.cjs')
            await script({github, context})
