name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The Github environment to be used - maps to cloud environment.
        required: true
        default: staging
        type: choice
        options:
          - staging
          - production
      scope:
        description: Scope of deployment (for preview environments)
        required: false
        type: string
      image-tag:
        description: image tag to deploy
        required: true
        type: string
      chart:
        description: chart to deploy
        required: true
        default: oci://stjudecloud.azurecr.io/charts/generic
      chart-version:
        description: chart version
        required: true
        default: 1.0.0
      values-file:
        description: values file for deployment
        required: true
        default: .devops/values/staging.yaml

jobs:
  deploy:
    runs-on: stjude-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: az login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.29.4

      - name: aks set staging context
        if: ${{ inputs.environment == 'staging' }}
        uses: azure/aks-set-context@v4
        with:
          cluster-name: aks-legacy-staging-eastus
          resource-group: rg-cluster-legacy-staging-eastus
          admin: "true"

      - name: aks set production context
        if: ${{ inputs.environment != 'staging' }}
        uses: azure/aks-set-context@v4
        with:
          cluster-name: stjude-${{ inputs.environment }}
          resource-group: rg${{ inputs.environment }}eastus
          admin: "true"

      - name: add helm repos
        run: |
          echo ${{ secrets.STJUDECLOUD_REGISTRY_PASSWORD }} | helm registry login ${{ secrets.STJUDECLOUD_REGISTRY_URL }} --username ${{ secrets.STJUDECLOUD_REGISTRY_USERNAME }} --password-stdin
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: helm diff
        run: |
          helm diff upgrade docs ${{ inputs.chart }} \
            --version ${{ inputs.chart-version }} \
            --namespace docs-${{ inputs.scope }} \
            --values {{ inputs.values-file }} \
            --set image.tag=${{ inputs.image-tag }} \
            --set datadog.env=${{ inputs.scope }} \
            --set datadog.service=docs \
            --allow-unreleased

      - name: helm upgrade
        run: |
          helm upgrade --install docs ${{ inputs.chart }} \
            --version ${{ inputs.chart-version }} \
            --namespace docs-${{ inputs.scope }} --create-namespace \
            --values {{ inputs.values-file }} \
            --set image.tag=${{ inputs.image-tag }} \
            --set datadog.env=${{ inputs.scope }} \
            --set datadog.service=docs \
            --atomic \
            --cleanup-on-fail \
            --history-max 25

      - name: helm history
        run: helm history docs --namespace docs-${{ inputs.scope }}

      - name: az logout
        run: |
          az logout
          az cache purge
          az account clear
