name: Markdown Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - content/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          globs: content/**/*.md
