name: Publish Release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    outputs:
      release_created: ${{ steps.release.outputs.created }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/jod
          cache: pnpm

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: stjudecloud-cloudy
          GIT_AUTHOR_EMAIL: <>
          GIT_COMMITTER_NAME: stjudecloud-cloudy
          GIT_COMMITER_EMAIL: <>
        run: |
          pnpm semantic-release
          if test -f .VERSION; then
            echo "created=true" >> $GITHUB_OUTPUT
          else
            echo "created=false" >> $GITHUB_OUTPUT
          fi

      - name: upload artifact
        if: ${{ hashFiles('.VERSION') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: .VERSION

  publish:
    needs: release
    if: ${{ needs.release.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: version

      - name: set version
        run: echo "VERSION=$(cat .VERSION)" >> $GITHUB_ENV

      - name: docker login
        run: echo "${{ secrets.STJUDECLOUD_REGISTRY_PASSWORD }}" | docker login ${{ secrets.STJUDECLOUD_REGISTRY_URL }} --username ${{ secrets.STJUDECLOUD_REGISTRY_USERNAME }} --password-stdin

      - name: tag release
        run: |
          docker pull ${{ secrets.STJUDECLOUD_REGISTRY_URL }}/${GITHUB_REPOSITORY}:latest
          docker tag ${{ secrets.STJUDECLOUD_REGISTRY_URL }}/${{ env.REPOSITORY }}:latest ${{ secrets.STJUDECLOUD_REGISTRY_URL }}/${{ env.REPOSITORY }}:v${{ env.VERSION }}
          docker push ${{ secrets.STJUDECLOUD_REGISTRY_URL }}/${{ env.REPOSITORY }}:v${{ env.VERSION }}
