name: Spell Check

on:
  pull_request:
    branches:
      - main
    paths:
      - content/**
      - .spelling

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: spellcheck
        uses: matheus23/md-spellcheck-action@v4.2.2
        with:
          files-to-check: content/**/**/*.md
          words-to-ignore-file: .spelling
