name: Update Tag

on:
  pull_request:
    types: [closed]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  tag-update:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: docker login
        run: echo "${{ secrets.STJUDECLOUD_REGISTRY_PASSWORD }}" | docker login ${{ secrets.STJUDECLOUD_REGISTRY_URL }} --username ${{ secrets.STJUDECLOUD_REGISTRY_USERNAME }} --password-stdin

      - name: tag images
        run: |
          PREVIOUS_SHA=`jq --raw-output .pull_request.head.sha $GITHUB_EVENT_PATH`
          NEW_SHA=`jq --raw-output .pull_request.merge_commit_sha $GITHUB_EVENT_PATH`
          REPO="${GITHUB_REPOSITORY}"
          VERSION="${GITHUB_REF_NAME##*@}"

          if docker manifest inspect ${{ secrets.STJUDECLOUD_REGISTRY_URL }}/${REPO}:${PREVIOUS_SHA::7} > /dev/null 2>&1 ; then
            docker pull ${{ secrets.STJUDECLOUD_REGISTRY_URL }}/${REPO}:${PREVIOUS_SHA::7}
            docker tag ${{ secrets.STJUDECLOUD_REGISTRY_URL }}/${REPO}:${PREVIOUS_SHA::7} ${{ secrets.STJUDECLOUD_REGISTRY_URL }}/${REPO}:${NEW_SHA::7}
            docker push ${{ secrets.STJUDECLOUD_REGISTRY_URL }}/${REPO} --all-tags
          fi
